name: Update Dockerhub Description

on:
  push:
    # TODO: restore before merge!
    # branches:
    #   - master
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

jobs:
  update-docker-hub-description:
    runs-on: ubuntu-latest

    steps:
      # checkout the repo to $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # update the docker hub description and overview
      - name: Dockerhub description and overview update
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: hetorusnl/python-poetry
          short-description: ${{ github.event.repository.description }}
